### ISSUE TITLE
[Feature] cfquery

### ISSUE THREAD

**Issue by AndrewKralovec** [Lafougere/node-cfml#8]
@Lafougere , do you think we should implement `<cfquery>`or is this overkill ?
I was thinking what we could do i import knex.js. This is what we can use to build the query. 
The user will be required to still setup a datasource, just like in cold fusion.
As far as building the query, we could just read the text block in the `<cfquery>` tag, and plug that string into knex as a raw query.

**Comment by devalnor** [comment]
I think **node-cfml** has to be a CFML based templating engine like **mustache**, **handlebear**, **pug**, etc... not another clone like ralio or lucee.

**Comment by AndrewKralovec** [comment]
@devalnor , that is a good point.
